[package]
name = "rfmt"
version = "0.1.0"
edition = "2021"
authors = ["fujitani sora <fujitanisora0414@gmail.com>"]
license = "MIT"
publish = false

[lib]
name = "rfmt"
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
